name: Build Pages
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Install mdbook
      run: sudo snap install mdbook
    - name: Build book
      run: mdbook build
    - name: Build pages
      run: cp -rf book/* ./
    - name: publish
      run: git add . && git commit -m 'auto build pages' && git push origin master