name: Build Pages
on:
  push:
    branches:
      - master
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Install mdbook
      run: |
            sudo apt update
            sudo apt install snapd
            sudo snap install mdbook
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        BUILD_SCRIPT: mdbook book
        FOLDER: book