name: Build Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.1'
          # mdbook-version: 'latest'

      - run: |
              mdbook build
              cp -rf book/* ./
              git config --global user.email "liaoymxsdl@gmail.com"
              git config --global user.name "baoyachi"
              git add .
              git commit -m 'auto publish'
              git push origin master

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.ACCESS_TOKEN }}
      #     publish_branch: master
      #     publish_dir: ./book
      #     allow_empty_commit: true