name: Build Pages
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
    # - name: Install Rust (rustup)
      # run: rustup update stable --no-self-update && rustup default stable
    # - name: Install mdbook
      # run: cargo install mdbook
    - name: Install mdbook
      run: apt-install mdbook
    - name: Build pages
      run: cp -rf book/* ./
    - name: publish
      run: git add . && git commit -m 'build pages' && git push origin master