name: Build Pages
on:
  push:
    branches:
      - master
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Install mdbook
      run: |
            rustup update stable --no-self-update && rustup default stable
            cargo install mdbook
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        BUILD_SCRIPT: ls -al && pwd && mdbook book
        FOLDER: book